modLoader = "lowcodefml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/NonConflictKeys/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_ALL_VERSION"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
